// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package _2AA4_A1;

import java.util.Map;
import java.util.HashMap;

/************************************************************/
/**
 * 
 */
public class Bank {
				/**
				 * 
				 */
				public Map<ResourceType, Integer> resourceList;
	/**
	 * 
	 */
	public Bank () {
		this.resourceList = new HashMap<>();
		for (ResourceType type : ResourceType.values()) {
			resourceList.put(type, 19); // Standard Catan: 19 of each resource
		}
	}
	/**
	 * 
	 * @return 
	 * @param t 
	 * @param n 
	 * @param p 
	 */
	public boolean giveResource(ResourceType t, int n, Player p) {
		Integer current = resourceList.get(t);
		if (current != null && current >= n) {
			resourceList.put(t, current - n);
			return true;
		}
		return false;
	}
	/**
	 * 
	 * @return 
	 * @param t 
	 * @param n 
	 * @param p 
	 */
	public boolean receiveResource(ResourceType t, int n, Player p) {
		Integer current = resourceList.get(t);
		if (current != null) {
			resourceList.put(t, current + n);
			return true;
		}
		return false;
	}
}
