// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package _2AA4_A1;

/************************************************************/
/**
 * 
 */
public class BuildStructure {
	private Player player;
	/**
	 * 
	 * @param p 
	 */
	public BuildStructure(Player p) {
		this.player = p;
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildSettlement(Node n) {
		if (n.isOccupied()) return false;
		if (player.removeResource(ResourceType.BRICK, 1) &&
			player.removeResource(ResourceType.LUMBER, 1) &&
			player.removeResource(ResourceType.GRAIN, 1) &&
			player.removeResource(ResourceType.WOOL, 1)) {
			n.owner = player;
			n.building = BuildingType.SETTLEMENT;
			player.addVictoryPoint(1);
			return true;
		}
		return false;
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildCity(Node n) {
		if (n.building == BuildingType.SETTLEMENT && n.owner == player) {
			if (player.removeResource(ResourceType.ORE, 3) &&
				player.removeResource(ResourceType.GRAIN, 2)) {
				n.building = BuildingType.CITY;
				player.addVictoryPoint(1); // Settlement (1) -> City (2) is +1 VP
				return true;
			}
		}
		return false;
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildRoad(Edge e) {
		if (e.isOccupied()) return false;
		if (player.removeResource(ResourceType.BRICK, 1) &&
			player.removeResource(ResourceType.LUMBER, 1)) {
			e.owner = player;
			e.building = BuildingType.ROAD;
			return true;
		}
		return false;
	}
	/**
	 * 
	 * @param Parameter1 
	 */
	public void giveVPs(Player Parameter1) {
		// Logic could be in checkWin or specific events
	}
}
