// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package _2AA4_A1;

/************************************************************/
/**
 * 
 */
public class Edge {
				/**
				 * 
				 */
				public int id;
				/**
				 * 
				 */
				public Player owner;
				/**
				 * 
				 */
				public BuildingType building;
	/**
	 * 
	 */
	public Edge(int id) {
		this.id = id;
	}
	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
		return owner != null;
	}
}
