// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4_A1;



/************************************************************/
/**
 * 
 */
public class Bank {
				/**
				 * 
				 */
				public EMap resourceList;
	/**
	 * 
	 */
	public void Bank () {
	}
	/**
	 * 
	 * @return 
	 * @param type 
	 * @param amount 
	 */
	public boolean hasResource(ResourceType type, int amount) {
	}
	/**
	 * 
	 * @return 
	 * @param type 
	 * @param amount 
	 */
	public boolean giveResource(ResourceType type, int amount) {
	}
	/**
	 * 
	 * @return 
	 * @param type 
	 * @param amount 
	 */
	public boolean receiveResource(ResourceType type, int amount) {
	}
}
