// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4_A1;



/************************************************************/
/**
 * 
 */
public class Board extends GameMaster
 {
				/**
				 * 
				 */
				private EEList Tiles;
				/**
				 * 
				 */
				private EEList Nodes;
				/**
				 * 
				 */
				private EEList Edges;
				/**
				 * 
				 */
				public HexTile[] hextile;
	/**
	 * 
	 */
	public void Board() {
	}
	/**
	 * 
	 * @return 
	 */
	public String getTile() {
	}
	/**
	 * 
	 * @return 
	 */
	public String getNodes() {
	}
	/**
	 * 
	 * @return 
	 */
	public String getEdges() {
	}
	/**
	 * 
	 * @param n 
	 * @return 
	 */
	public boolean isValidSettlement(Node n) {
	}
	/**
	 * 
	 * @param e 
	 * @return 
	 */
	public boolean isValidRoad(Edge e) {
	}
	/**
	 * 
	 * @param n 
	 * @return 
	 */
	public EEList getAdjacentTiles(Node n) {
	}
	/**
	 * 
	 */
	public void updateBoard() {
	}
}
