// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4_A1;



/************************************************************/
/**
 * 
 */
public class BuildStructure extends Player
 {
	/**
	 * 
	 * @param p 
	 */
	public void BuildStructure(Player p) {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildSettlement() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildCity() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildRoad() {
	}
	/**
	 * 
	 */
	public void giveVPs() {
	}
}
