// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.Random;

/************************************************************/
/**
 * 
 */
public class Die {
	private Random random = new Random();
	/**
	 * 
	 */
	public int Die1;
	/**
	 * 
	 */
	public int Die2;

	/**
	 * 
	 */
	public Die() {
	}

	/**
	 * 
	 * @return 
	 */
	public int Roll() {
		Die1 = random.nextInt(6) + 1;
		Die2 = random.nextInt(6) + 1;
		return Die1 + Die2;
	}
}
