// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4_A1;



/************************************************************/
/**
 * 
 */
public class Die {
				/**
				 * 
				 */
				public Die Die1;
				/**
				 * 
				 */
				public Die Die2;
	/**
	 * 
	 * @param Die1 
	 * @param Die2 
	 */
	public void Die(Die Die1, Die Die2) {
	}
	/**
	 * 
	 * @return 
	 */
	public int Roll() {
	}
}
