// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4_A1;



/************************************************************/
/**
 * 
 */
public class GameMaster {
				/**
				 * 
				 */
				private int currentPlayerIndex;
				/**
				 * 
				 */
				private int dice1;
				/**
				 * 
				 */
				private int dice2;
				/**
				 * 
				 */
				private boolean gameOver;
				/**
				 * 
				 */
				private int winningVP;
				/**
				 * 
				 */
				public Player[] player;
				/**
				 * 
				 */
				public Bank bank;
	/**
	 * 
	 */
	public void GameMaster() {
	}
	/**
	 * 
	 */
	public void startGame() {
	}
	/**
	 * 
	 */
	public void nextTurn() {
	}
	/**
	 * 
	 */
	public void getCurrentPlayer() {
	}
	/**
	 * 
	 * @return 
	 */
	public int rollDice() {
	}
	/**
	 * 
	 * @param roll 
	 */
	public void distributeResources(int roll) {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean tradeWithBank() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildRoad() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildSettlement() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildCity() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean checkWin() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean isGameOver() {
	}
}
