// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4_A1;



/************************************************************/
/**
 * 
 */
public class GameMaster {
				/**
				 * 
				 */
				private int currentPlayerIndex;
				/**
				 * 
				 */
				private int dice1;
				/**
				 * 
				 */
				private int dice2;
				/**
				 * 
				 */
				private boolean gameOver;
				/**
				 * 
				 */
				private int winningVP;
				/**
				 * 
				 */
				public Player[] player;
				/**
				 * 
				 */
				public Bank bank;
				/**
				 * 
				 */
				public Board board;
	/**
	 * 
	 */
	public GameMaster() {
		currentPlayerIndex = 0;
		gameOver = false;
		winningVP = 10;
		dice1 = 0;
		dice2 = 0;
	}
	/**
	 * 
	 */
	public void startGame() {
		bank = new Bank();
		board = new Board();
		currentPlayerIndex = 0;
		gameOver = false;
	}
	/**
	 * 
	 */
	public void nextTurn() {
		if (player != null && player.length > 0) {
			currentPlayerIndex = (currentPlayerIndex + 1) % player.length;
		}
	}
	/**
	 * 
	 * @return 
	 */
	public Player getCurrentPlayer() {
		if (player != null && currentPlayerIndex >= 0 && currentPlayerIndex < player.length) {
			return player[currentPlayerIndex];
		}
		return null;
	}
	/**
	 * 
	 * @return 
	 */
	public int rollDice() {
		dice1 = (int)(Math.random() * 6) + 1;
		dice2 = (int)(Math.random() * 6) + 1;
		return dice1 + dice2;
	}
	/**
	 * 
	 * @param roll 
	 */
	public void distributeResources(int roll) {
		for (HexTile tile : map.getTiles()) {
            if (tile.getTokenNumber() != roll) continue;

            ResourceType resource = tile.getResource();

            for (Node node : tile.getNodes()) {
                if (node.isOccupied() && bank.giveResource(resource, 1)) {
                    node.getOwner().addResource(resource, 1);
                }
            }
        }
	}
	/**
	 * 
	 * @return 
	 */
	public boolean tradeWithBank() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildRoad() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildSettlement() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildCity() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean checkWin() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean isGameOver() {
	}

	public void handlePlayersWithMoreThanSevenCards() {
    	for (Player player : players) {
            if (player.getTotalResources() > 7) {
                player.build();
            }
        }
    }
}
