// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public class GameMaster {
				/**
				 * 
				 */
				private int currentPlayerIndex;
				/**
				 * 
				 */
				private int dice1;
				/**
				 * 
				 */
				private int dice2;
				/**
				 * 
				 */
				private boolean gameOver;
				/**
				 * 
				 */
				private int winningVP = 10;
				/**
				 * 
				 */
				public Player[] player;
				/**
				 * 
				 */
				public Bank bank;
				/**
				 * 
				 */
				public Die die;
				/**
				 * 
				 */
				public Board board;

	/**
	 * 
	 * @param b 
	 * @param p 
	 * @param bk 
	 */
	public GameMaster(Board b, Player[] p, Bank bk) {
		this.board = b;
		this.player = p;
		this.bank = bk;
		this.die = new Die();
		this.currentPlayerIndex = 0;
		this.gameOver = false;
	}
	/**
	 * 
	 */
	public void startGame() {
		System.out.println("Catan Game Started!");
	}
	/**
	 * 
	 */
	public void nextTurn() {
		currentPlayerIndex = (currentPlayerIndex + 1) % player.length;
	}
	/**
	 * 
	 * @return 
	 */
	public Player getCurrentPlayer() {
		return player[currentPlayerIndex];
	}
	/**
	 * 
	 * @return 
	 */
	public int rollDice() {
		int roll = die.Roll();
		this.dice1 = die.Die1;
		this.dice2 = die.Die2;
		return roll;
	}
	/**
	 * 
	 * @param roll 
	 */
	public void distributeResources(int roll) {
		if (roll == 7) {
			// Discard logic could go here
			return;
		}
		for (HexTile tile : board.hextile) {
			if (tile.TokenNumber != null && tile.TokenNumber.getValue() == roll) {
				for (Node node : tile.nodesList) {
					if (node.isOccupied()) {
						int amount = (node.building == BuildingType.CITY) ? 2 : 1;
						if (bank.giveResource(tile.resource, amount, node.owner)) {
							node.owner.addResource(tile.resource, amount);
						}
					}
				}
			}
		}
	}
	/**
	 * 
	 * @return 
	 */
	public boolean tradeWithBank(ResourceType give, ResourceType get) {
		Player p = getCurrentPlayer();
		if (p.removeResource(give, 4)) {
			if (bank.giveResource(get, 1, p)) {
				p.addResource(get, 1);
				bank.receiveResource(give, 4, p);
				return true;
			} else {
				// Refund
				p.addResource(give, 4);
			}
		}
		return false;
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildRoad(Edge e) {
		BuildStructure bs = new BuildStructure(getCurrentPlayer());
		return bs.buildRoad(e);
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildSettlement(Node n) {
		BuildStructure bs = new BuildStructure(getCurrentPlayer());
		return bs.buildSettlement(n);
	}
	/**
	 * 
	 * @return 
	 */
	public boolean buildCity(Node n) {
		BuildStructure bs = new BuildStructure(getCurrentPlayer());
		return bs.buildCity(n);
	}
	/**
	 * 
	 * @return 
	 * @param p 
	 */
	public boolean checkWin(Player p) {
		if (p.getVictoryPoints() >= winningVP) {
			gameOver = true;
			return true;
		}
		return false;
	}
	/**
	 * 
	 * @return 
	 */
	public boolean isGameOver() {
		return gameOver;
	}
}
