// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class HexTile {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public ResourceType resource;
	/**
	 * 
	 */
	public List<Node> nodesList;
	/**
	 * 
	 */
	public List<Edge> edgesList;
	/**
	 * 
	 */
	public TokenNumber TokenNumber;
	/**
	 * 
	 */
	public Edge[] edge;
	/**
	 * 
	 */
	public Node[] node;

	/**
	 * 
	 * @param res
	 * @param tn
	 */
	public HexTile(ResourceType res, TokenNumber tn) {
		this.resource = res;
		this.TokenNumber = tn;
		this.nodesList = new ArrayList<>();
		this.edgesList = new ArrayList<>();
	}

	/**
	 * 
	 * @param tn 
	 * @param d 
	 */
	public void resourceProduction(TokenNumber tn, Die d) {
		// This logic is mostly moved to GameMaster.distributeResources
		// but we can keep a reference here if needed.
	}
}
