// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4_A1;



/************************************************************/
/**
 * 
 */
public class HexTile {
				/**
				 * 
				 */
				public int id;
				/**
				 * 
				 */
				public ResourceType resource;
				/**
				 * 
				 */
				public EEList Nodes;
				/**
				 * 
				 */
				public EEList Edges;
				/**
				 * 
				 */
				public TokenNumber TokenNumber;
				/**
				 * 
				 */
				public Edge[] edge;
				/**
				 * 
				 */
				public Node[] node;
	/**
	 * 
	 * @param resource 
	 */
	public void HexTile(undef resource) {
	}
	/**
	 * 
	 */
	public void resourceProduction() {
	}
}
