// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4_A1;



/************************************************************/
/**
 * 
 */
public class Node {
				/**
				 * 
				 */
				public int id;
				/**
				 * 
				 */
				public undef owner;
				/**
				 * 
				 */
				public undef building;
	/**
	 * 
	 */
	public void Node() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
	}
}
