// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4_A1;

public class Player {
	private int victoryPoint;
	private Board<PieceType, Integer> piecesOwned;
	private Board<ResourceType, Integer> resourceOwned;
	private String name;
	
	public void Player(String name) {
		this.name = name;
		victoryPoint = 2;
	}
	
	public void getCurrentResources() {
		return resourceOwned;
	}
	public int getVictoryPoints() {
		return victoryPoint;
	}
	public void build() {
	}
}
