// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4_A1;



/************************************************************/
/**
 * 
 */
public class Player {
				/**
				 * 
				 */
				private int victoryPoint;
				/**
				 * 
				 */
				private undef piecesOwned;
				/**
				 * 
				 */
				private undef resourcedOwned;
	/**
	 * 
	 */
	public void Player() {
	}
	/**
	 * 
	 */
	public void getCurrentResources() {
	}
	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}
	/**
	 * 
	 */
	public void build() {
	}
}
