// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package 2AA4_A1;

public class Player {
	private int victoryPoint;
	private Board<PieceType, Integer> piecesOwned;
	private Board<ResourceType, Integer> resourceOwned;
	private String name;
	
	public Player() {					//constructor to initialize variables
		this.victoryPoint = 2;
		this.piecesOwned = new ArrayList<>();
		this.resourcedOwned = new HashMap<>();
		for (ResourceType type : ResourceType.values()) {
			resourcedOwned.put(type, 0);
		}
		this.name = "Unknown";
	}

	public Player(String name) {
		this();
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public Map<ResourceType, Integer> getCurrentResources() {
		return resourcedOwned;
	}

	public int getVictoryPoints() {
		return victoryPoint;
	}

	public void addVictoryPoints(int points) {
		this.victoryPoint += points;
	}

	public void addResource(ResourceType type, int amount) { //ADDED
        hand.merge(type, amount, Integer::sum);
    }

    public int getTotalResources() { //ADDED
        int total = 0;
        for (int count : hand.values()) {
            total += count;
        }
        return total;
    }
}
