// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package A1;

/**
 * Enumeration representing different types of game pieces.
 */
public enum BuildingType {
	ROAD,
	SETTLEMENT,
	CITY
	;
}
