// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package A1;

/**
 * 
 */
public class Edge {
				public int id;
				public undef owner;
				public undef building;
	/**
	 * 
	 */
	public void Edge() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
	}
}
