// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package A1;

/**
 * Class representing a node in the game board.
 */
public class Node {
				public int id;
				public undef owner;
				public undef building;
	/**
	 * Default constructor for Node.
	 */
	public void Node() {
	}
	/**
	 * Checks if the node is occupied by a player.
	 * @return true if occupied, false otherwise
	 */
	public boolean isOccupied() {
	}
}
