// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package A1;

/**
 * Enumeration representing different resource types in the game.
 */
public enum ResourceType {
	GRAIN,
	BRICK,
	ORE,
	LUMBER,
	WOOL
	;
}
