// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package _2AA4_A1;

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Board {
				/**
				 * 
				 */
				private List<HexTile> Tiles;
				/**
				 * 
				 */
				private List<Node> Nodes;
				/**
				 * 
				 */
				private List<Edge> Edges;
				/**
				 * 
				 */
				public HexTile[] hextile;
	/**
	 * 
	 */
	public Board() {
		this.Tiles = new ArrayList<>();
		this.Nodes = new ArrayList<>();
		this.Edges = new ArrayList<>();
	}
	/**
	 * 
	 * @return 
	 */
	public String getTile() {
		return "Tiles count: " + Tiles.size();
	}
	/**
	 * 
	 * @return 
	 */
	public String getNodes() {
		return "Nodes count: " + Nodes.size();
	}
	/**
	 * 
	 * @return 
	 */
	public String getEdges() {
		return "Edges count: " + Edges.size();
	}
	/**
	 * 
	 * @param n 
	 * @return 
	 */
	public boolean isValidSettlement(Node n) {
		if (n.isOccupied()) return false;
		// Distance rule: no adjacent nodes can be occupied
		// (Requires connectivity mapping, skipping for basic simulation)
		return true;
	}
	/**
	 * 
	 * @param e 
	 * @return 
	 */
	public boolean isValidRoad(Edge e) {
		if (e.isOccupied()) return false;
		return true;
	}
	/**
	 * 
	 * @param n 
	 * @return 
	 */
	public List<HexTile> getAdjacentTiles(Node n) {
		List<HexTile> adjacent = new ArrayList<>();
		for (HexTile tile : Tiles) {
			if (tile.nodesList.contains(n)) {
				adjacent.add(tile);
			}
		}
		return adjacent;
	}
	/**
	 * 
	 */
	public void updateBoard() {
		// Update logic
	}

	public void addTile(HexTile tile) {
		Tiles.add(tile);
	}

	public void setHexTilesArray(HexTile[] tiles) {
		this.hextile = tiles;
		for (HexTile t : tiles) {
			Tiles.add(t);
		}
	}
}
