// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package _2AA4_A1;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Player {
				/**
				 * 
				 */
				private int victoryPoint;
				/**
				 * 
				 */
				private List<BuildingType> piecesOwned;
				/**
				 * 
				 */
				private Map<ResourceType, Integer> resourcesOwned;
				/**
				 * 
				 */
				private String name;

	/**
	 * 
	 */
	public Player(String name) {
		this.name = name;
		this.victoryPoint = 0;
		this.piecesOwned = new ArrayList<>();
		this.resourcesOwned = new HashMap<>();
		for (ResourceType type : ResourceType.values()) {
			resourcesOwned.put(type, 0);
		}
	}

	/**
	 * 
	 * @return 
	 */
	public Map<ResourceType, Integer> getCurrentResources() {
		return resourcesOwned;
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
		return victoryPoint;
	}

	public void addVictoryPoint(int points) {
		this.victoryPoint += points;
	}

	public void addResource(ResourceType type, int amount) {
		resourcesOwned.put(type, resourcesOwned.get(type) + amount);
	}

	public boolean removeResource(ResourceType type, int amount) {
		if (resourcesOwned.get(type) >= amount) {
			resourcesOwned.put(type, resourcesOwned.get(type) - amount);
			return true;
		}
		return false;
	}

	/**
	 * 
	 */
	public void build() {
		// Building logic handled in GameMaster/BuildStructure
	}

	public String getName() {
		return name;
	}
}
